### ISSUE TITLE
Code of Conduct / Social Rules?

### ISSUE THREAD

**Issue by ablwr** [XFRCollective/Administrative#1]
Consider adding a [CoC/anti-harassment policy](https://geekfeminism.org/about/code-of-conduct/) or [social rules statement](https://www.recurse.com/manual#sub-sec-social-rules)?

**Comment by dinahhandel** [comment]
This is a great comment and idea, Ashley. We've been working on a statement that outlines our values as a collective, which will include an action plan for instances when those values are compromised. Not everyone in xfr is on GitHub yet, so this issue will remain open until more people can comment. Once we finish our statement, that will be shared here as well. I really appreciate your input!

**Comment by dinahhandel** [comment]
I'm going to close this issue because we have added a Code of Conduct (https://github.com/XFRCollective/Administrative/blob/master/CodeofConduct.md). Please open a new issue if there are further questions or comments about the document.
